### PR TITLE
Arduino 1.00+ compatible and some other changes

### PR DESCRIPTION
**Pull request by jej**
Just few changes to make it 1.00+ compatible, and permit infinite pulse.

### CODE REVIEW

**Comment by fpapadopou** [comment]
Hi there! I'd like to use this library with codebender (Arduino 1.0.5 compatible). Is there any chance that you merge this pull request? Thanks :)

**Comment by jej** [comment]
Changes are not so big to have it compatible with 1.00+...

Just replace _#include "WProgram.h"_ by _#include "Arduino.h"_

See https://github.com/carlynorama/Arduino-Library-FancyLED/commit/e6c09ab8ba81f0ab46a57bd7a1d7b684fd5e0e6f

Cheers

**Comment by soif** [comment]
Hi. Just a little bump to @fpapadopou suggestion. 

It would be nice if anyone could still use your useful library, without having to patch it ( e6c09ab ). Thanks 👍

**Comment by jej** [comment]
Just fork it from here https://github.com/jej/Arduino-Library-FancyLED

:)

**Comment by soif** [comment]
Thank you Jej, I know how to do it. ;-) . 
I just intended to make life easier for beginners... :-/

**Pull request closed without merging**
